In [1]:
import numpy as np

In [2]:
np.array([x for x in range(0,100)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
a = np.array([x for x in range(1,6)])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.size

5

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
a.ndim

1

In [8]:
a.dtype

dtype('int64')

In [9]:
a.shape

(5,)

In [10]:
b = np.array([[x for x in range(1, 11)], [x for x in range(1, 11)], [x for x in range(1, 11)]])

In [11]:
b.shape

(3, 10)

In [12]:
b.ndim

2

In [13]:
b.size

30

In [14]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [15]:
a + 10

array([11, 12, 13, 14, 15])

In [16]:
np.multiply(b, 3)

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [17]:
b = np.array([6, 7, 8, 9, 10])

In [18]:
a + b

array([ 7,  9, 11, 13, 15])

In [19]:
a - b

array([-5, -5, -5, -5, -5])

In [20]:
a = np.array([1,2,3,4,5])

In [21]:
a.dtype

dtype('int64')

In [22]:
a = np.array([1, 2, 3, 4, 5], dtype = float)

In [23]:
a

array([1., 2., 3., 4., 5.])

In [24]:
np.array([True, True, False])

array([ True,  True, False])

In [25]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.empty(10)

array([1.14250098e-313, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.90179131e-310, 6.34783719e-066, 2.14330454e+184, 6.20155159e-091,
       6.75826020e-067, 6.90187520e-310])

In [31]:
np.random.randint(1, 28, 50)

array([12, 10, 10,  9, 12, 15,  5, 11, 10,  2,  1, 22,  7, 14, 18, 16, 21,
       26,  5, 16,  8,  3, 22,  7, 14,  4, 15, 15, 10, 22, 15, 17, 13, 21,
        9, 18, 26, 12, 16, 10,  2,  2,  5, 26, 20, 27,  5,  5, 23, 26])

In [32]:
np.empty(10)

array([1.14250098e-313, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.90179131e-310, 6.34783719e-066, 2.14330454e+184, 6.20155159e-091,
       6.75826020e-067, 6.90187520e-310])

In [33]:
a = np.random.randint(0, 10, 10)

In [34]:
a

array([8, 7, 9, 3, 1, 8, 0, 9, 6, 6])

In [35]:
a[0:3]

array([8, 7, 9])

In [36]:
a[-6:]

array([1, 8, 0, 9, 6, 6])

In [37]:
a[0] = 19

In [38]:
a

array([19,  7,  9,  3,  1,  8,  0,  9,  6,  6])

In [39]:
a = np.random.randint(0, 100, 20)

In [40]:
a

array([48, 27, 83, 53, 23, 25, 83, 16, 56, 79, 50, 32, 96, 13, 65,  5, 29,
       61, 25, 12])

In [41]:
a[:5]

array([48, 27, 83, 53, 23])

In [42]:
#a[start, end, hops]
a[:10]

array([48, 27, 83, 53, 23, 25, 83, 16, 56, 79])

In [43]:
a[0]

48

In [44]:
a[1]

27

In [45]:
a[3]

53

In [46]:
a[[0,4,7,5]]

array([48, 23, 16, 25])

In [47]:
b = np.array([1,2,3,4,5])

In [48]:
b

array([1, 2, 3, 4, 5])

In [49]:
b[[True, True, False, True, False]]

array([1, 2, 4])

In [50]:
a = np.random.randint(1, 100, 100)

In [51]:
a

array([65,  3, 15, 58, 29, 66,  2, 68, 64, 67, 87, 65, 29, 59, 96, 63, 70,
       16, 74, 28,  8, 63, 53, 37,  4, 27, 67, 83, 21, 98, 57, 68, 69, 12,
       41, 31, 74, 11,  9, 35, 49, 20, 12, 86, 18, 44, 73, 40, 70, 59, 22,
       78, 57, 88,  7, 26, 12, 27, 13, 31, 34, 57, 13,  4, 49, 43, 13, 60,
       55, 37, 57, 43, 74, 55, 88,  2, 85,  7, 28, 35, 35, 86, 23, 85, 76,
       96,  4, 12, 56, 67, 84, 94,  2, 60, 76, 18,  8, 11, 71, 57])

In [52]:
def operacion(valor):
    """Eleva al cuadrado el argumento recibido por valor y le suma dos"""
    return (valor ** 2) + 2

In [53]:
for valor in a:
    print(operacion(valor))

4227
11
227
3366
843
4358
6
4626
4098
4491
7571
4227
843
3483
9218
3971
4902
258
5478
786
66
3971
2811
1371
18
731
4491
6891
443
9606
3251
4626
4763
146
1683
963
5478
123
83
1227
2403
402
146
7398
326
1938
5331
1602
4902
3483
486
6086
3251
7746
51
678
146
731
171
963
1158
3251
171
18
2403
1851
171
3602
3027
1371
3251
1851
5478
3027
7746
6
7227
51
786
1227
1227
7398
531
7227
5778
9218
18
146
3138
4491
7058
8838
6
3602
5778
326
66
123
5043
3251


In [54]:
vector = np.vectorize(operacion)

In [55]:
vector(a)

array([4227,   11,  227, 3366,  843, 4358,    6, 4626, 4098, 4491, 7571,
       4227,  843, 3483, 9218, 3971, 4902,  258, 5478,  786,   66, 3971,
       2811, 1371,   18,  731, 4491, 6891,  443, 9606, 3251, 4626, 4763,
        146, 1683,  963, 5478,  123,   83, 1227, 2403,  402,  146, 7398,
        326, 1938, 5331, 1602, 4902, 3483,  486, 6086, 3251, 7746,   51,
        678,  146,  731,  171,  963, 1158, 3251,  171,   18, 2403, 1851,
        171, 3602, 3027, 1371, 3251, 1851, 5478, 3027, 7746,    6, 7227,
         51,  786, 1227, 1227, 7398,  531, 7227, 5778, 9218,   18,  146,
       3138, 4491, 7058, 8838,    6, 3602, 5778,  326,   66,  123, 5043,
       3251])

In [56]:
vector = np.vectorize(lambda valor: (valor ** 3 ) + 2)

In [57]:
vector(a)

array([274627,     29,   3377, 195114,  24391, 287498,     10, 314434,
       262146, 300765, 658505, 274627,  24391, 205381, 884738, 250049,
       343002,   4098, 405226,  21954,    514, 250049, 148879,  50655,
           66,  19685, 300765, 571789,   9263, 941194, 185195, 314434,
       328511,   1730,  68923,  29793, 405226,   1333,    731,  42877,
       117651,   8002,   1730, 636058,   5834,  85186, 389019,  64002,
       343002, 205381,  10650, 474554, 185195, 681474,    345,  17578,
         1730,  19685,   2199,  29793,  39306, 185195,   2199,     66,
       117651,  79509,   2199, 216002, 166377,  50655, 185195,  79509,
       405226, 166377, 681474,     10, 614127,    345,  21954,  42877,
        42877, 636058,  12169, 614127, 438978, 884738,     66,   1730,
       175618, 300765, 592706, 830586,     10, 216002, 438978,   5834,
          514,   1333, 357913, 185195])

In [58]:
a = np.arange(0, 9)

In [59]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
#copias
a_1 = a.copy()

In [61]:
a_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
id(a)

139696094821472

In [63]:
id(a_1)

139696094819952

In [64]:
a is a_1

False

In [65]:
a[0] = 100

In [66]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [67]:
a_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
a.view()

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [69]:
a_v = a.view()

In [70]:
id(a)

139696094821472

In [71]:
id(a_v)

139696094836736

In [72]:
a is a_v

False

In [73]:
a[0] = 14

In [74]:
a

array([14,  1,  2,  3,  4,  5,  6,  7,  8])

In [75]:
a_v

array([14,  1,  2,  3,  4,  5,  6,  7,  8])

In [76]:
a_v[-1] = 180

In [77]:
a_v

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [78]:
a

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [79]:
a_v.base

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [80]:
id(a)

139696094821472

In [81]:
id(a_v.base)

139696094821472

In [82]:
d = a[:]

In [83]:
a

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [84]:
d

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [85]:
d.base

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [86]:
d.base is a

True

In [87]:
#añadir o quitar elementos de arreglos. No modifican los arreglos, crean un objeto arreglo aparte
a = np.random.randint(1, 11, 10)

In [88]:
a

array([6, 5, 1, 9, 6, 7, 4, 5, 3, 4])

In [89]:
np.insert(a, 0, 200)

array([200,   6,   5,   1,   9,   6,   7,   4,   5,   3,   4])

In [90]:
np.append(a, 200)

array([  6,   5,   1,   9,   6,   7,   4,   5,   3,   4, 200])

In [91]:
#eliminar elementos
np.delete(a, -1)

array([6, 5, 1, 9, 6, 7, 4, 5, 3])

In [92]:
a.size

10

In [93]:
np.resize(a, 11)

array([6, 5, 1, 9, 6, 7, 4, 5, 3, 4, 6])

In [94]:
a

array([6, 5, 1, 9, 6, 7, 4, 5, 3, 4])

In [95]:
b = np.array([10, 20, 30, 40, 50])

In [96]:
np.concatenate([a, b])

array([ 6,  5,  1,  9,  6,  7,  4,  5,  3,  4, 10, 20, 30, 40, 50])

In [97]:
a = np.random.randint(0, 11, 100)

In [98]:
a.sort()

In [99]:
a

array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10])

In [100]:
a = a[::-1]

In [101]:
a

array([10, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        8,  8,  8,  8,  7,  7,  7,  7,  7,  7,  7,  7,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0])

In [102]:
b = np.random.randint(1, 100, 20)

In [103]:
b

array([77, 52, 73, 11, 32, 83, 74, 57, 45, 56, 77, 72, 53, 26, 38, 34, 93,
       99, 95, 81])

In [104]:
np.sort(b)

array([11, 26, 32, 34, 38, 45, 52, 53, 56, 57, 72, 73, 74, 77, 77, 81, 83,
       93, 95, 99])

In [105]:
np.sort(b)[::-1]

array([99, 95, 93, 83, 81, 77, 77, 74, 73, 72, 57, 56, 53, 52, 45, 38, 34,
       32, 26, 11])

In [106]:
#Matrices

In [107]:
A = np.array([
    [1,2,3,4,5], 
    [10, 20, 30, 40, 50], 
    [100, 200, 300, 400, 500]
    ])

In [108]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [109]:
A.ndim

2

In [110]:
A.shape

(3, 5)

In [111]:
A[0][0]

1

In [112]:
A[1][2]

30

In [113]:
A[2][4]

500

In [114]:
A[0,0]

1

In [115]:
A[1,2]

30

In [116]:
A[2,4]

500

In [117]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [118]:
A[1, :3]

array([10, 20, 30])

In [119]:
A[2, 2:]

array([300, 400, 500])

In [120]:
A[0, [0, 4]]

array([1, 5])

In [121]:
A[:, 3]

array([  4,  40, 400])

In [122]:
A[[0, 2], 4]

array([  5, 500])

In [123]:
A.shape

(3, 5)

In [124]:
A.std()

157.21323099535866

In [125]:
A.sum()

1665

In [126]:
A.min()

1

In [127]:
A.max()

500

In [128]:
A.mean()

111.0

In [129]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [130]:
A[:, 0]

array([  1,  10, 100])

In [131]:
A[0, :]

array([1, 2, 3, 4, 5])

In [132]:
A[0, :1]

array([1])

In [133]:
A.transpose()

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500]])

In [134]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [135]:
A[:, 4].sum()

555

In [136]:
A.T[4].sum()

555

In [137]:
A.shape

(3, 5)

In [138]:
A.T.shape

(5, 3)

In [139]:
#Filtros
a = np.random.randint(1,11, 50)

In [140]:
a

array([ 4,  6,  8,  8, 10,  6,  1,  4,  4,  5,  1, 10,  9,  5,  5,  1,  8,
        8,  8,  8, 10,  9,  9,  2, 10,  6,  6,  3,  5,  1,  2,  1,  1,  6,
        1,  7,  3,  5,  7,  5,  2, 10, 10,  3,  4,  5,  9, 10,  4,  8])

In [141]:
a > 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [142]:
a = np.random.randint(10, 101, 50)

In [143]:
a

array([13, 56, 33, 43, 64, 56, 50, 18, 31, 87, 64, 77, 43, 59, 50, 40, 25,
       75, 45, 36, 58, 90, 11, 63, 59, 50, 56, 69, 85, 75, 41, 64, 89, 97,
       97, 87, 76, 83, 31, 65, 66, 38, 45, 82, 76, 10, 89, 80, 46, 62])

In [144]:
a > 50

array([False,  True, False, False,  True,  True, False, False, False,
        True,  True,  True, False,  True, False, False, False,  True,
       False, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True, False,  True])

In [145]:
b = a > 50

In [146]:
b

array([False,  True, False, False,  True,  True, False, False, False,
        True,  True,  True, False,  True, False, False, False,  True,
       False, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True, False,  True])

In [147]:
c = a[b]

In [148]:
c

array([56, 64, 56, 87, 64, 77, 59, 75, 58, 90, 63, 59, 56, 69, 85, 75, 64,
       89, 97, 97, 87, 76, 83, 65, 66, 82, 76, 89, 80, 62])

In [150]:
np.all(a > 50)

False

In [151]:
np.all(a > 0)

True

In [152]:
np.any((a >= 0) & (a <= 100))

True

In [153]:
np.any(a > 10)

True

In [154]:
np.any(a = 10)

True

In [156]:
calificaciones = np.array([7,8,5,6,9,10, 3, 5, 6, 8, 9, 10])

In [157]:
np.where(calificaciones >= 7, 'Felicidades', 'Lo sentimos, no aprobaste')

array(['Felicidades', 'Felicidades', 'Lo sentimos, no aprobaste',
       'Lo sentimos, no aprobaste', 'Felicidades', 'Felicidades',
       'Lo sentimos, no aprobaste', 'Lo sentimos, no aprobaste',
       'Lo sentimos, no aprobaste', 'Felicidades', 'Felicidades',
       'Felicidades'], dtype='<U25')

In [164]:
condicion = [(calificaciones == 10), ((calificaciones == 8) | (calificaciones == 9)), (calificaciones == 7), (calificaciones < 7)]

In [165]:
opciones = ["Sacaste 10!!", 'Felicidades', 'Aprobaste', 'Reprobaste, puto']

In [166]:
np.select(condicion, opciones)

array(['Aprobaste', 'Felicidades', 'Reprobaste, puto', 'Reprobaste, puto',
       'Felicidades', 'Sacaste 10!!', 'Reprobaste, puto',
       'Reprobaste, puto', 'Reprobaste, puto', 'Felicidades',
       'Felicidades', 'Sacaste 10!!'], dtype='<U21')