In [2]:
import numpy as np

In [3]:
np.array([x for x in range(0,100)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
a = np.array([x for x in range(1,6)])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.size

5

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
a.ndim

1

In [9]:
a.dtype

dtype('int64')

In [10]:
a.shape

(5,)

In [11]:
b = np.array([[x for x in range(1, 11)], [x for x in range(1, 11)], [x for x in range(1, 11)]])

In [12]:
b.shape

(3, 10)

In [13]:
b.ndim

2

In [14]:
b.size

30

In [15]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
a + 10

array([11, 12, 13, 14, 15])

In [17]:
np.multiply(b, 3)

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [18]:
b = np.array([6, 7, 8, 9, 10])

In [19]:
a + b

array([ 7,  9, 11, 13, 15])

In [20]:
a - b

array([-5, -5, -5, -5, -5])

In [21]:
a = np.array([1,2,3,4,5])

In [22]:
a.dtype

dtype('int64')

In [23]:
a = np.array([1, 2, 3, 4, 5], dtype = float)

In [24]:
a

array([1., 2., 3., 4., 5.])

In [25]:
np.array([True, True, False])

array([ True,  True, False])

In [26]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.empty(10)

array([1.14098110e-313, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.92449667e-310, 2.46655861e+184, 7.48392573e-067, 4.75876064e-090,
       5.70094499e-038, 6.92454241e-310])

In [32]:
np.random.randint(1, 28, 50)

array([22, 10, 12, 20, 13, 16,  7, 15, 21, 11,  3, 10, 24, 11,  8, 21, 24,
       19, 26, 12, 24, 20, 10, 21, 24,  6, 20, 18,  9, 23, 10, 26, 21, 27,
       13, 15, 11,  1, 26, 18,  6,  2, 23, 15, 14, 21, 16, 26, 21,  1])

In [33]:
np.empty(10)

array([1.14098110e-313, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.92449667e-310, 2.46655861e+184, 7.48392573e-067, 4.75876064e-090,
       5.70094499e-038, 6.92454241e-310])

In [34]:
a = np.random.randint(0, 10, 10)

In [35]:
a

array([5, 3, 5, 4, 6, 6, 5, 9, 9, 5])

In [36]:
a[0:3]

array([5, 3, 5])

In [37]:
a[-6:]

array([6, 6, 5, 9, 9, 5])

In [38]:
a[0] = 19

In [39]:
a

array([19,  3,  5,  4,  6,  6,  5,  9,  9,  5])

In [40]:
a = np.random.randint(0, 100, 20)

In [41]:
a

array([11, 24, 88, 98, 47, 57, 16, 30, 52, 55, 52, 86, 33, 23, 88, 55, 41,
       18, 19, 69])

In [42]:
a[:5]

array([11, 24, 88, 98, 47])

In [43]:
#a[start, end, hops]
a[:10]

array([11, 24, 88, 98, 47, 57, 16, 30, 52, 55])

In [44]:
a[0]

11

In [45]:
a[1]

24

In [46]:
a[3]

98

In [47]:
a[[0,4,7,5]]

array([11, 47, 30, 57])

In [48]:
b = np.array([1,2,3,4,5])

In [49]:
b

array([1, 2, 3, 4, 5])

In [50]:
b[[True, True, False, True, False]]

array([1, 2, 4])

In [51]:
a = np.random.randint(1, 100, 100)

In [52]:
a

array([47, 48, 36, 84, 83, 97, 77,  8, 38, 31, 19,  2, 25, 69, 77, 87, 23,
       50, 46, 56, 41, 24, 76, 97, 48, 72, 41, 61, 70,  8, 62, 87, 20, 57,
       21, 36, 59, 11, 28, 69, 18, 71,  6, 18,  5,  3, 99, 47, 82, 45, 70,
       36, 42, 24, 52, 64, 76, 56, 72, 97, 43,  8, 15, 91, 56, 30, 23,  6,
       63, 85, 40, 98, 15, 85, 93, 29, 24, 15, 86, 91, 58, 87, 22, 93, 75,
       89, 17, 37, 16, 16,  5, 10, 50, 93, 73, 88,  2, 97, 20, 63])

In [53]:
def operacion(valor):
    """Eleva al cuadrado el argumento recibido por valor y le suma dos"""
    return (valor ** 2) + 2

In [54]:
for valor in a:
    print(operacion(valor))

2211
2306
1298
7058
6891
9411
5931
66
1446
963
363
6
627
4763
5931
7571
531
2502
2118
3138
1683
578
5778
9411
2306
5186
1683
3723
4902
66
3846
7571
402
3251
443
1298
3483
123
786
4763
326
5043
38
326
27
11
9803
2211
6726
2027
4902
1298
1766
578
2706
4098
5778
3138
5186
9411
1851
66
227
8283
3138
902
531
38
3971
7227
1602
9606
227
7227
8651
843
578
227
7398
8283
3366
7571
486
8651
5627
7923
291
1371
258
258
27
102
2502
8651
5331
7746
6
9411
402
3971


In [55]:
vector = np.vectorize(operacion)

In [56]:
vector(a)

array([2211, 2306, 1298, 7058, 6891, 9411, 5931,   66, 1446,  963,  363,
          6,  627, 4763, 5931, 7571,  531, 2502, 2118, 3138, 1683,  578,
       5778, 9411, 2306, 5186, 1683, 3723, 4902,   66, 3846, 7571,  402,
       3251,  443, 1298, 3483,  123,  786, 4763,  326, 5043,   38,  326,
         27,   11, 9803, 2211, 6726, 2027, 4902, 1298, 1766,  578, 2706,
       4098, 5778, 3138, 5186, 9411, 1851,   66,  227, 8283, 3138,  902,
        531,   38, 3971, 7227, 1602, 9606,  227, 7227, 8651,  843,  578,
        227, 7398, 8283, 3366, 7571,  486, 8651, 5627, 7923,  291, 1371,
        258,  258,   27,  102, 2502, 8651, 5331, 7746,    6, 9411,  402,
       3971])

In [57]:
vector = np.vectorize(lambda valor: (valor ** 3 ) + 2)

In [58]:
vector(a)

array([103825, 110594,  46658, 592706, 571789, 912675, 456535,    514,
        54874,  29793,   6861,     10,  15627, 328511, 456535, 658505,
        12169, 125002,  97338, 175618,  68923,  13826, 438978, 912675,
       110594, 373250,  68923, 226983, 343002,    514, 238330, 658505,
         8002, 185195,   9263,  46658, 205381,   1333,  21954, 328511,
         5834, 357913,    218,   5834,    127,     29, 970301, 103825,
       551370,  91127, 343002,  46658,  74090,  13826, 140610, 262146,
       438978, 175618, 373250, 912675,  79509,    514,   3377, 753573,
       175618,  27002,  12169,    218, 250049, 614127,  64002, 941194,
         3377, 614127, 804359,  24391,  13826,   3377, 636058, 753573,
       195114, 658505,  10650, 804359, 421877, 704971,   4915,  50655,
         4098,   4098,    127,   1002, 125002, 804359, 389019, 681474,
           10, 912675,   8002, 250049])

In [59]:
a = np.arange(0, 9)

In [60]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
#copias
a_1 = a.copy()

In [62]:
a_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
id(a)

140155742096400

In [64]:
id(a_1)

140155742096880

In [65]:
a is a_1

False

In [66]:
a[0] = 100

In [67]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [68]:
a_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
a.view()

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [70]:
a_v = a.view()

In [71]:
id(a)

140155742096400

In [72]:
id(a_v)

140155742144272

In [73]:
a is a_v

False

In [74]:
a[0] = 14

In [75]:
a

array([14,  1,  2,  3,  4,  5,  6,  7,  8])

In [76]:
a_v

array([14,  1,  2,  3,  4,  5,  6,  7,  8])

In [77]:
a_v[-1] = 180

In [78]:
a_v

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [79]:
a

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [80]:
a_v.base

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [81]:
id(a)

140155742096400

In [82]:
id(a_v.base)

140155742096400

In [83]:
d = a[:]

In [84]:
a

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [85]:
d

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [86]:
d.base

array([ 14,   1,   2,   3,   4,   5,   6,   7, 180])

In [87]:
d.base is a

True

In [88]:
#añadir o quitar elementos de arreglos. No modifican los arreglos, crean un objeto arreglo aparte
a = np.random.randint(1, 11, 10)

In [89]:
a

array([3, 4, 2, 2, 6, 2, 8, 6, 3, 5])

In [90]:
np.insert(a, 0, 200)

array([200,   3,   4,   2,   2,   6,   2,   8,   6,   3,   5])

In [91]:
np.append(a, 200)

array([  3,   4,   2,   2,   6,   2,   8,   6,   3,   5, 200])

In [92]:
#eliminar elementos
np.delete(a, -1)

array([3, 4, 2, 2, 6, 2, 8, 6, 3])

In [93]:
a.size

10

In [94]:
np.resize(a, 11)

array([3, 4, 2, 2, 6, 2, 8, 6, 3, 5, 3])

In [95]:
a

array([3, 4, 2, 2, 6, 2, 8, 6, 3, 5])

In [96]:
b = np.array([10, 20, 30, 40, 50])

In [97]:
np.concatenate([a, b])

array([ 3,  4,  2,  2,  6,  2,  8,  6,  3,  5, 10, 20, 30, 40, 50])

In [98]:
a = np.random.randint(0, 11, 100)

In [99]:
a.sort()

In [100]:
a

array([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,
        6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [101]:
a = a[::-1]

In [102]:
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  8,  8,  8,  8,  8,  8,  8,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  6,  6,  6,  6,  6,  6,  6,  6,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4,  4,  4,  4,  4,  4,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0])

In [103]:
b = np.random.randint(1, 100, 20)

In [104]:
b

array([53, 25, 94, 22, 85, 75, 27, 20, 78, 53, 90, 69, 87, 61, 83, 50, 43,
       56, 37, 43])

In [105]:
np.sort(b)

array([20, 22, 25, 27, 37, 43, 43, 50, 53, 53, 56, 61, 69, 75, 78, 83, 85,
       87, 90, 94])

In [106]:
np.sort(b)[::-1]

array([94, 90, 87, 85, 83, 78, 75, 69, 61, 56, 53, 53, 50, 43, 43, 37, 27,
       25, 22, 20])

In [107]:
#Matrices

In [108]:
A = np.array([
    [1,2,3,4,5], 
    [10, 20, 30, 40, 50], 
    [100, 200, 300, 400, 500]
    ])

In [109]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [110]:
A.ndim

2

In [111]:
A.shape

(3, 5)

In [112]:
A[0][0]

1

In [113]:
A[1][2]

30

In [114]:
A[2][4]

500

In [115]:
A[0,0]

1

In [116]:
A[1,2]

30

In [117]:
A[2,4]

500

In [118]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [119]:
A[1, :3]

array([10, 20, 30])

In [120]:
A[2, 2:]

array([300, 400, 500])

In [121]:
A[0, [0, 4]]

array([1, 5])

In [122]:
A[:, 3]

array([  4,  40, 400])

In [123]:
A[[0, 2], 4]

array([  5, 500])

In [124]:
A.shape

(3, 5)

In [125]:
A.std()

157.21323099535866

In [126]:
A.sum()

1665

In [127]:
A.min()

1

In [128]:
A.max()

500

In [129]:
A.mean()

111.0

In [130]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [131]:
A[:, 0]

array([  1,  10, 100])

In [132]:
A[0, :]

array([1, 2, 3, 4, 5])

In [133]:
A[0, :1]

array([1])

In [134]:
A.transpose()

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500]])

In [135]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [136]:
A[:, 4].sum()

555

In [137]:
A.T[4].sum()

555

In [138]:
A.shape

(3, 5)

In [139]:
A.T.shape

(5, 3)

In [140]:
#Filtros
a = np.random.randint(1,11, 50)

In [141]:
a

array([ 7,  5,  5, 10,  9,  7,  8,  4, 10,  3,  4,  3,  9,  5,  9,  3,  7,
        5, 10,  9,  8,  2,  4,  3,  3,  4,  8,  7,  2,  9, 10, 10,  8,  7,
        6,  5,  4,  1,  2,  4, 10,  6,  3,  9,  8,  9, 10,  7,  2,  6])

In [142]:
a > 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [143]:
a = np.random.randint(10, 101, 50)

In [144]:
a

array([ 96,  19,  97,  20,  10,  80,  37,  95,  32,  22,  95, 100,  55,
        45,  63,  67,  52, 100,  19,  98,  82,  27,  11,  10,  32,  96,
        27,  36,  71, 100,  10,  12,  39,  50,  34,  84,  87,  48,  56,
        52,  99,  38,  35,  77,  13,  41,  39,  13,  70,  90])

In [145]:
a > 50

array([ True, False,  True, False, False,  True, False,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False, False, False, False,  True,
        True, False,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True])

In [146]:
b = a > 50

In [147]:
b

array([ True, False,  True, False, False,  True, False,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False, False, False, False,  True,
        True, False,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True])

In [148]:
c = a[b]

In [149]:
c

array([ 96,  97,  80,  95,  95, 100,  55,  63,  67,  52, 100,  98,  82,
        96,  71, 100,  84,  87,  56,  52,  99,  77,  70,  90])

In [150]:
np.all(a > 50)

False

In [151]:
np.all(a > 0)

True

In [152]:
np.any((a >= 0) & (a <= 100))

True

In [153]:
np.any(a > 10)

True

In [154]:
np.any(a = 10)

True

In [155]:
calificaciones = np.array([7,8,5,6,9,10, 3, 5, 6, 8, 9, 10])

In [156]:
np.where(calificaciones >= 7, 'Felicidades', 'Lo sentimos, no aprobaste')

array(['Felicidades', 'Felicidades', 'Lo sentimos, no aprobaste',
       'Lo sentimos, no aprobaste', 'Felicidades', 'Felicidades',
       'Lo sentimos, no aprobaste', 'Lo sentimos, no aprobaste',
       'Lo sentimos, no aprobaste', 'Felicidades', 'Felicidades',
       'Felicidades'], dtype='<U25')

In [157]:
condicion = [(calificaciones == 10), ((calificaciones == 8) | (calificaciones == 9)), (calificaciones == 7), (calificaciones < 7)]

In [158]:
opciones = ["Sacaste 10!!", 'Felicidades', 'Aprobaste', 'Reprobaste, puto']

In [159]:
np.select(condicion, opciones)

array(['Aprobaste', 'Felicidades', 'Reprobaste, puto', 'Reprobaste, puto',
       'Felicidades', 'Sacaste 10!!', 'Reprobaste, puto',
       'Reprobaste, puto', 'Reprobaste, puto', 'Felicidades',
       'Felicidades', 'Sacaste 10!!'], dtype='<U21')

In [161]:
a = np.random.randint(0, 10, 10)

In [162]:
a

array([6, 6, 3, 2, 4, 8, 4, 9, 7, 9])

In [164]:
np.savetxt("arreglo.txt", a)

In [165]:
ls

arreglo.txt  Numpy.ipynb


In [166]:
# %load arreglo.txt
6.000000000000000000e+00
6.000000000000000000e+00
3.000000000000000000e+00
2.000000000000000000e+00
4.000000000000000000e+00
8.000000000000000000e+00
4.000000000000000000e+00
9.000000000000000000e+00
7.000000000000000000e+00
9.000000000000000000e+00


In [167]:
a

array([6, 6, 3, 2, 4, 8, 4, 9, 7, 9])

In [168]:
np.savetxt("arreglo.txt", a, fmt = '%i')

In [169]:
# %load arreglo.txt
6
6
3
2
4
8
4
9
7
9


In [170]:
np.loadtxt('arreglo.txt')

array([6., 6., 3., 2., 4., 8., 4., 9., 7., 9.])

In [172]:
np.loadtxt('arreglo.txt').dtype

dtype('float64')

In [174]:
b = np.loadtxt('arreglo.txt', dtype = int)

In [175]:
c = a.reshape((2,5))

In [176]:
c

array([[6, 6, 3, 2, 4],
       [8, 4, 9, 7, 9]])

In [183]:
np.savetxt("matrix.csv", c, delimiter = ',' ,fmt = '%i')

In [184]:
# %load matrix.csv
6,6,3,2,4
8,4,9,7,9


In [188]:
d = np.loadtxt("matrix.csv", delimiter = ',', dtype = int)

In [189]:
d

array([[6, 6, 3, 2, 4],
       [8, 4, 9, 7, 9]])

In [190]:
np.save("arreglo_bin.npy", a)

In [192]:
e = np.load("arreglo_bin.npy")

In [193]:
e

array([6, 6, 3, 2, 4, 8, 4, 9, 7, 9])

In [194]:
e_v = e.view()

In [195]:
e_v

array([6, 6, 3, 2, 4, 8, 4, 9, 7, 9])

In [196]:
e = e.reshape((2, 5))

In [197]:
e

array([[6, 6, 3, 2, 4],
       [8, 4, 9, 7, 9]])

In [198]:
e_v

array([6, 6, 3, 2, 4, 8, 4, 9, 7, 9])