In [12]:
import numpy as np

In [13]:
np.array([x for x in range(0,100)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
a = np.array([x for x in range(1,6)])

In [15]:
type(a)

numpy.ndarray

In [16]:
a.size

5

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
a.ndim

1

In [19]:
a.dtype

dtype('int64')

In [20]:
a.shape

(5,)

In [24]:
b = np.array([[x for x in range(1, 11)], [x for x in range(1, 11)], [x for x in range(1, 11)]])

In [25]:
b.shape

(3, 10)

In [26]:
b.ndim

2

In [27]:
b.size

30

In [28]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [29]:
a + 10

array([11, 12, 13, 14, 15])

In [31]:
np.multiply(b, 3)

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [32]:
b = np.array([6, 7, 8, 9, 10])

In [33]:
a + b

array([ 7,  9, 11, 13, 15])

In [34]:
a - b

array([-5, -5, -5, -5, -5])

In [35]:
a = np.array([1,2,3,4,5])

In [36]:
a.dtype

dtype('int64')

In [37]:
a = np.array([1, 2, 3, 4, 5], dtype = float)

In [38]:
a

array([1., 2., 3., 4., 5.])

In [39]:
np.array([True, True, False])

array([ True,  True, False])

In [44]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [45]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [51]:
np.empty(10)

array([4.67714488e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.94762642e-310, 8.32236056e-071, 3.27044296e+179, 6.81737931e-091,
       8.84195564e+165, 6.94767385e-310])

In [62]:
np.random.randint(1, 28, 50)

array([12, 24,  3, 21,  9,  3,  6, 23, 21, 19,  5,  5, 20, 27,  8, 15,  5,
       19, 19, 11,  7,  6,  3,  3, 15,  4,  9,  9,  6,  4,  6,  5,  1,  8,
       20, 24, 12,  8,  2, 10, 27, 23,  3, 20,  4,  5, 15, 17, 22, 10])

In [64]:
np.empty(10)

array([4.67714488e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.94762642e-310, 8.32236056e-071, 3.27044296e+179, 6.81737931e-091,
       8.84195564e+165, 6.94767385e-310])

In [65]:
a = np.random.randint(0, 10, 10)

In [66]:
a

array([4, 2, 9, 9, 3, 8, 2, 0, 8, 2])

In [68]:
a[0:3]

array([4, 2, 9])

In [69]:
a[-6:]

array([3, 8, 2, 0, 8, 2])

In [70]:
a[0] = 19

In [71]:
a

array([19,  2,  9,  9,  3,  8,  2,  0,  8,  2])

In [72]:
a = np.random.randint(0, 100, 20)

In [73]:
a

array([34, 21, 62, 95, 98, 53, 17, 41, 70, 25, 76, 98, 20, 53,  7, 37, 10,
       60, 35, 29])

In [75]:
a[:5]

array([34, 21, 62, 95, 98])

In [78]:
#a[start, end, hops]
a[:10]

array([34, 21, 62, 95, 98, 53, 17, 41, 70, 25])

In [79]:
a[0]

34

In [80]:
a[1]

21

In [81]:
a[3]

95

In [82]:
a[[0,4,7,5]]

array([34, 98, 41, 53])

In [83]:
b = np.array([1,2,3,4,5])

In [84]:
b

array([1, 2, 3, 4, 5])

In [85]:
b[[True, True, False, True, False]]

array([1, 2, 4])

In [86]:
a = np.random.randint(1, 100, 100)

In [87]:
a

array([ 4, 95, 35, 54,  7, 24, 15, 67,  7, 53, 28, 29, 90, 86, 46, 84, 89,
       45, 77, 29, 22, 71,  9, 71, 70, 86, 25, 87, 50, 82, 35, 97,  1, 85,
        4, 42, 70, 43, 91, 12, 89, 64, 25, 69, 88, 94, 96, 14, 94, 15, 36,
       77, 62, 13, 90, 32, 40,  5, 91, 81, 10, 14, 30, 63, 48, 98, 99, 80,
        3,  5, 93, 72, 57,  7, 24, 64, 24, 53,  1, 92, 30, 13, 64, 53, 22,
       81, 98, 72, 65, 48, 49, 62, 18, 40, 45, 47, 89, 72,  6, 82])

In [89]:
def operacion(valor):
    """Eleva al cuadrado el argumento recibido por valor y le suma dos"""
    return (valor ** 2) + 2

In [91]:
for valor in a:
    print(operacion(valor))

18
9027
1227
2918
51
578
227
4491
51
2811
786
843
8102
7398
2118
7058
7923
2027
5931
843
486
5043
83
5043
4902
7398
627
7571
2502
6726
1227
9411
3
7227
18
1766
4902
1851
8283
146
7923
4098
627
4763
7746
8838
9218
198
8838
227
1298
5931
3846
171
8102
1026
1602
27
8283
6563
102
198
902
3971
2306
9606
9803
6402
11
27
8651
5186
3251
51
578
4098
578
2811
3
8466
902
171
4098
2811
486
6563
9606
5186
4227
2306
2403
3846
326
1602
2027
2211
7923
5186
38
6726


In [92]:
vector = np.vectorize(operacion)

In [93]:
vector(a)

array([  18, 9027, 1227, 2918,   51,  578,  227, 4491,   51, 2811,  786,
        843, 8102, 7398, 2118, 7058, 7923, 2027, 5931,  843,  486, 5043,
         83, 5043, 4902, 7398,  627, 7571, 2502, 6726, 1227, 9411,    3,
       7227,   18, 1766, 4902, 1851, 8283,  146, 7923, 4098,  627, 4763,
       7746, 8838, 9218,  198, 8838,  227, 1298, 5931, 3846,  171, 8102,
       1026, 1602,   27, 8283, 6563,  102,  198,  902, 3971, 2306, 9606,
       9803, 6402,   11,   27, 8651, 5186, 3251,   51,  578, 4098,  578,
       2811,    3, 8466,  902,  171, 4098, 2811,  486, 6563, 9606, 5186,
       4227, 2306, 2403, 3846,  326, 1602, 2027, 2211, 7923, 5186,   38,
       6726])

In [94]:
vector = np.vectorize(lambda valor: (valor ** 3 ) + 2)

In [95]:
vector(a)

array([    66, 857377,  42877, 157466,    345,  13826,   3377, 300765,
          345, 148879,  21954,  24391, 729002, 636058,  97338, 592706,
       704971,  91127, 456535,  24391,  10650, 357913,    731, 357913,
       343002, 636058,  15627, 658505, 125002, 551370,  42877, 912675,
            3, 614127,     66,  74090, 343002,  79509, 753573,   1730,
       704971, 262146,  15627, 328511, 681474, 830586, 884738,   2746,
       830586,   3377,  46658, 456535, 238330,   2199, 729002,  32770,
        64002,    127, 753573, 531443,   1002,   2746,  27002, 250049,
       110594, 941194, 970301, 512002,     29,    127, 804359, 373250,
       185195,    345,  13826, 262146,  13826, 148879,      3, 778690,
        27002,   2199, 262146, 148879,  10650, 531443, 941194, 373250,
       274627, 110594, 117651, 238330,   5834,  64002,  91127, 103825,
       704971, 373250,    218, 551370])